[window]
padding               = { x = 12, y = 12 }
decorations           = "None"

[font]
normal                = { family = "HackNerdFontMono Nerd Font", style = "Regular" }
size                  = 14

[keyboard]
bindings = [
  { key = "Left", mods = "Alt", chars = "\u001BB" },
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Command", chars = "\u001bOH", mode = "AppCursor" },
  { key = "Right", mods = "Command", chars = "\u001bOF", mode = "AppCursor" },
  { key = "Back", mods = "Command", chars = "\u0015" },
  { key = "Back", mods = "Alt", chars = "\u001b\u007f" },
  { key = "c", mods = "Command", action = "Copy" },
]

# OneNord theme
[colors.primary]
background = "#2a303c"
foreground = "#d8dee9"

[colors.normal]
black   = "#3b4252"
red     = "#bf616a"
green   = "#a3be8c"
yellow  = "#ebcb8b"
blue    = "#81a1c1"
magenta = "#b48ead"
cyan    = "#88c0d0"
white   = "#e5e9f0"

[colors.bright]
black   = "#4c566a"
red     = "#bf616a"
green   = "#a3be8c"
yellow  = "#ebcb8b"
blue    = "#81a1c1"
magenta = "#b48ead"
cyan    = "#8fbcbb"
white   = "#eceff4"

[colors.selection]
text = "#eceff4"
background = "#4c566a"

